version: "3.8"

services:
  database:
    image: postgres:13.4-alpine
    container_name: microservices.postgres.localhost
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=microservices
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432